import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  images: {
    remotePatterns: [
      { hostname: 'cdn.meryembalkan.com.tr' },
    ],
  },
  serverExternalPackages: ['iyzipay', 'postman-request'],
  outputFileTracingIncludes: {
    '/**': [
      './node_modules/iyzipay/**/*',
      './node_modules/postman-request/**/*',
      './node_modules/extend/**/*',
      './node_modules/aws-sign2/**/*',
      './node_modules/aws4/**/*',
      './node_modules/caseless/**/*',
      './node_modules/combined-stream/**/*',
      './node_modules/forever-agent/**/*',
      './node_modules/form-data/**/*',
      './node_modules/http-signature/**/*',
      './node_modules/is-typedarray/**/*',
      './node_modules/isstream/**/*',
      './node_modules/json-stringify-safe/**/*',
      './node_modules/mime-types/**/*',
      './node_modules/mime-db/**/*',
      './node_modules/oauth-sign/**/*',
      './node_modules/performance-now/**/*',
      './node_modules/qs/**/*',
      './node_modules/safe-buffer/**/*',
      './node_modules/tunnel-agent/**/*',
      './node_modules/asynckit/**/*',
      './node_modules/delayed-stream/**/*',
      './node_modules/sshpk/**/*',
      './node_modules/assert-plus/**/*',
      './node_modules/dashdash/**/*',
      './node_modules/jsprim/**/*',
      './node_modules/tweetnacl/**/*',
      './node_modules/jsbn/**/*',
      './node_modules/ecc-jsbn/**/*',
      './node_modules/psl/**/*',
      './node_modules/punycode/**/*',
      './node_modules/@postman/**/*',
      './node_modules/url-parse/**/*',
      './node_modules/requires-port/**/*',
      './node_modules/querystringify/**/*',
      './node_modules/universalify/**/*',
      './node_modules/stream-length/**/*',
      './node_modules/agent-base/**/*',
      './node_modules/asn1/**/*',
      './node_modules/bcrypt-pbkdf/**/*',
      './node_modules/bluebird/**/*',
      './node_modules/call-bind-apply-helpers/**/*',
      './node_modules/call-bound/**/*',
      './node_modules/core-util-is/**/*',
      './node_modules/debug/**/*',
      './node_modules/dunder-proto/**/*',
      './node_modules/es-define-property/**/*',
      './node_modules/es-errors/**/*',
      './node_modules/es-object-atoms/**/*',
      './node_modules/extsprintf/**/*',
      './node_modules/function-bind/**/*',
      './node_modules/get-intrinsic/**/*',
      './node_modules/get-proto/**/*',
      './node_modules/getpass/**/*',
      './node_modules/gopd/**/*',
      './node_modules/has-symbols/**/*',
      './node_modules/hasown/**/*',
      './node_modules/ip-address/**/*',
      './node_modules/json-schema/**/*',
      './node_modules/math-intrinsics/**/*',
      './node_modules/ms/**/*',
      './node_modules/object-inspect/**/*',
      './node_modules/safer-buffer/**/*',
      './node_modules/side-channel/**/*',
      './node_modules/side-channel-list/**/*',
      './node_modules/side-channel-map/**/*',
      './node_modules/side-channel-weakmap/**/*',
      './node_modules/smart-buffer/**/*',
      './node_modules/socks/**/*',
      './node_modules/socks-proxy-agent/**/*',
      './node_modules/uuid/**/*',
      './node_modules/verror/**/*',
    ],
  },
  async headers() {
    return [
      {
        source: '/(.*)',
        headers: [
          {
            key: 'Content-Security-Policy',
            value: [
              "default-src 'self'",
              "script-src 'self' 'unsafe-inline' 'unsafe-eval'",
              "style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com",
              "img-src 'self' data: blob: https://cdn.meryembalkan.com.tr https://www.meryembalkan.com.tr https://*.supabase.co",
              "media-src 'self' https://cdn.meryembalkan.com.tr",
              "font-src 'self' https://cdnjs.cloudflare.com https://fonts.gstatic.com",
              "frame-src https://www.google.com https://maps.google.com",
              "frame-ancestors 'self'",
              "connect-src 'self' https://*.supabase.co https://fonts.googleapis.com",
              "object-src 'none'",
              "base-uri 'self'",
            ].join('; '),
          },
          {
            key: 'Strict-Transport-Security',
            value: 'max-age=63072000; includeSubDomains',
          },
          {
            key: 'Permissions-Policy',
            value: 'camera=(), microphone=(), geolocation=(), browsing-topics=()',
          },
          {
            key: 'X-Content-Type-Options',
            value: 'nosniff',
          },
          {
            key: 'X-Frame-Options',
            value: 'SAMEORIGIN',
          },
          {
            key: 'Referrer-Policy',
            value: 'strict-origin-when-cross-origin',
          },
        ],
      },
    ];
  },
};

export default nextConfig;
