import type { Metadata } from "next";
import { Geist, Geist_Mono, Pacifico } from "next/font/google";
import "./globals.css";
import PageTransition from "./components/PageTransition";
import { Toaster } from "sonner";

const pacifico = Pacifico({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-pacifico",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Meryem Balkan",
  description: "Generated by Mustafa Aydın",
  icons: {
    icon: "/images/AnaSayfa/Meryem_Balkan_Logo.jpg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="tr" suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${pacifico.variable} antialiased`}
      >
        <PageTransition />
        {children}

        {/* 🔥 Toaster burada olmalı */}
        <Toaster position="top-right" richColors closeButton />
      </body>
    </html>
  );
}
